---
title: ''
bibliography: '../library.bib'
csl: '../gbt7714_1987.csl'
reference-section-title: "Reference"
output:
  custom_docx_document:
    reference_docx: ./formal_temple.docx
---

```{r setup, include=FALSE}
library(officedown)
library(flextable)
knitr::opts_chunk$set(echo = F, fig.cap = TRUE, message = F, print = F)
```

# 致谢 {-}

&emsp;&emsp; 
仰观宇宙之大，星空之繁盛，感动于科学如月夜般诱人，化学如银河般辽阔，分子如星瀚般灿烂，而人类亦如群星般璀璨，所以我将方法取名为多重化学星云（MCnebula），以资自励——这当然是骗人的，它之所以叫这么个名字，是因为我初次使用 'fr' 布局并将子网络以 'grid' 绘制，它刚好分成了好多星云般的形状，一团团的，仅此而已。有趣吗？在Nebula出现之前的步骤中，还有一个叫做 'Stardust Classes' 的名称，为什么要叫这个名称呢？因为这里需要一个定义名，而那时候我刚好想到了曾经的某个动漫里的某张卡牌名称叫 'Stardust Dragon'，'Stardust' 听起来挺有音律的美的，而刚好它又和 'Nebula' 有那么些关联，它就这么被我拍案决定了。'Nebula' 和 'Stardust' 听起来都挺酷，然而终究它们的灵感好像和浪漫毫不搭边。

&emsp;&emsp; 
我在做这个课题的时候，无形中遵循了某种美学——也许是两种，一种是效率，另一种是优雅。凡是让我动用鼠标的，都不够效率；凡是无法让我用回车键重复的，都不够优雅。效率和优雅逐渐成为我坐在计算机面前的本能。为了它们，我逐渐和最初要做的内容南辕北辙了，最终老师乃至我自己都不太明白我最终要做什么了。它误打误撞，带着些侥幸——当然还有我的导师虽然对我的行为一头雾水但一直勤于推动的原因——它最终还是有了那么个成型；它之所以能成型，也许是因为我追求的效率和优雅，其他人也或多或少地在追求吧，只是我比较一意孤行。我为了效率和优雅，耗时耗力地去摸索和本课题没有任何关联的 'VIM'，它终究是一个初学者连输入都做不到的编辑器……它是效率和优雅的最佳践行者，计算机世界里最古老的福音，我比感谢R语言要更加感谢它，没有它，我根本无法想象那逾越上万行、牵一发动全身的代码要如何实现。除了感谢VIM，我还得感谢Linux，感谢Ubuntu和它的发行版Pop!_OS，它们让我明白了计算机可以这么酷，这个世界里不是只有Windows称雄，它们才是舞台上最耀眼的明星。我还得感谢R语言，感谢 'ggplot2'，感谢 'apply' 家族，它们各自是优雅和效率最忠实的拥趸，它们让我一直昂扬着激情的斗志去编程。我还得感谢 'grid' 包，它让我脱离了鼠标去拼图组图，在最后的时间里，它让我编程于办公的领域里加上了最后一块拼图——虽然它让我耗费的时间也快让老师们急疯了。我还得感谢 'method' 包，它让我享受了一番面向对象编程的快乐，让我如太空站的架构师一样去设计一个 'mcnebula' 的类……对R和R包们的感谢说之不尽，但就到这里吧。现在我得感谢SIRIUS，感谢ZODIAC，感谢CSI:FingerID，感谢CANOPUS，它们让我站在巨人们的肩膀上看见质谱和化学接壤的混沌（也因为它们而脱离了手动分析的苦海），我也因为它们而最初接触了编程，它们也让我知道了那些像孩子们一样去对待科学的人，否则他们不会取SIRIUS、ZODIAC这样的名字。

&emsp;&emsp; 
我可能给我们的老师们增添了很多烦恼，因为我异想天开胜于实干，脚下总是如履薄冰——我自找的。但是老师们总是以师德和慷慨包容了我，一直在做科研雾海里的灯塔。吕老师在刚开始的时候指导我用质谱做分析，他带我进入了GNPS构建的分析世界，让我接触了分子网络，也因此有了后来的Nebula的雏形。王老师在我撰写文章的时候提供了很多帮助，她总是用耐心和委婉的话语化解我某时的激进，鼓励我继续做下去，她像个朋友一样和我平等的对话。单老师曾经谈心般地说，有了方向就坚持做下去，不要太在意别人的看法；她还在我寒假罢工不肯干的时候说了超多鼓励的话，虽然我超级顽固听不进去。感谢这些老师的鼓励和帮助。在我像个鸵鸟一样钻进编程之前，我还做过点分子机制相关的，做过点动物实验相关的，做过点药物提取相关的，做过炮制工艺相关的——这么看来，我可能是实验室里“交际最广”的学生了——我在好多老师的帮助下展开过实验：在一切还未开始的时候，郝老师带我接触了第一个项目；在我确定硕士课题之后——虽然最后背道而驰了——桑老师和我一起漫长地提炼了杜仲；在动物实验开展的时候，杨老师披袍上阵教我做手术；做分子机制了，我因此把分子室弄得一团糟，但韩老师还是耐心地没有罢黜我；我好像还接触了点细胞实验，因为打鱼又晒网，学了点皮毛都算不上，但和各位老师和务正业的同学们都有了交流，他们为我提供了许多帮助，只怪我自己不争气……我还得感谢各位同门师兄妹们，虽然我性格比较孤僻，几乎没有给他们谈心谈话的机会，但他们每每在我终于肯离开分析的座位动手实验时提供了贴心的帮助；原谅我，就不一一列举他们的名字了。最后，我郑重感谢曹老师，他日理万机，但总是不忘在穿梭实验室之余，坐到我旁边的座位上敦促我实验的进展，关心我是否遇到哪些困难；虽然我一意孤行，每每在他敦促后的当晚熬夜去解决那些与实验和课题几乎毫无关联的旁枝末节。

&emsp;&emsp; 
感谢曾经共事过的一切，感谢所有的老师和同学，祝你们身体健康，万事如意。


