grid.newpage()
## over title
pushViewport(viewport(layout = grid.layout(30, 1), name = "panel"))
pushViewport(viewport(layout.pos.row = 1, name = "title"))
## ------------------------------------- 
pushViewport(viewport(layout = grid.layout(1, 2)))
pushViewport(viewport(layout.pos.col = 2, name = "cross_title", clip = "on"))
grid.draw(title_rect)
title_gp <- gpar(col = "white", cex = 1.2, fontfamily = "Times", fontface = "bold")
grid.text("Cross filter", gp = title_gp)
## ------------------------------------- 
popViewport()
pushViewport(viewport(layout.pos.col = 1, name = "simple_filter"))
pushViewport(viewport(layout = grid.layout(1, 5)))
pushViewport(viewport(layout.pos.col = 1:3, name = "inner_filter", clip = "on"))
grid.draw(title_rect)
grid.text("Inner filter", gp = title_gp)
## ------------------------------------- 
popViewport()
pushViewport(viewport(layout.pos.col = 4:5, name = "create_stardust"))
grid.draw(roundrectGrob(0.5, 0.4, 0.95, 0.95,
                        gp = gpar(fill = "#E18727FF"), r = unit(0.1, "npc")))
grid.text("Stardust classes", gp = title_gp)
## ---------------------------------------------------------------------- 
upViewport(0)
downViewport("panel")
pushViewport(viewport(layout.pos.row = 3:30, name = "plot"))
pushViewport(viewport(layout = grid.layout(1, 2), name = "start"))
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1, name = "inner"))
pushViewport(viewport(layout = grid.layout(1, 5)))
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1:3, name = "step1"))
print(p1, newpage = F)
## ------------------------------------- 
popViewport()
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 4:5, name = "step2"))
pushViewport(viewport(layout = grid.layout(1, 10)))
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1:2, name = "arrow"))
grid.segments(0.5, 0.03, 0.5, 0.97, gp = gpar(col = "grey"))
## ------------------------------------- 
popViewport()
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 3:10, name = "net"))
pushViewport(viewport(layout = grid.layout(length(lst) + 1, 1)))
mapply(lst, 1:length(lst),
    FUN = function(obj, n){
      print(obj, vp = viewport(layout.pos.row = n, layout.pos.col = 1), newpage = F)
    })
## ------------------------------------- 
upViewport(0)
downViewport("start")
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 2, name = "cross"))
pushViewport(viewport(layout = grid.layout(3, 1), name = "cross3"))
## ------------------------------------- 
subtitle_gp <- gpar(col = "black", cex = 1, fontfamily = "Times", fontface = "bold")
module <- roundrectGrob(width = 0.98, height = 0.98, r = unit(0.05, "npc"))
## ------------------------------------- 
pushViewport(viewport(layout.pos.row = 1, name = "quantity"))
grid.draw(module)
pushViewport(viewport(layout = grid.layout(5, 3)))
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1, name = "subtitle_1"))
grid.text("Quantity", gp = subtitle_gp)
popViewport()
pushViewport(viewport(layout.pos.row = 2:5, layout.pos.col = 1:3, name = "fig1"))
pushViewport(viewport(layout = grid.layout(1, 3), name = "fig1.layout"))

pushViewport(viewport(layout.pos.col = 1:2, name = "fig1.1"))
pushViewport(viewport(layout = grid.layout(1, 10)))
pushViewport(viewport(layout.pos.col = 1:3))
grid.draw(few.rect)
print(p.peak.yellow, vp = few.rect_vp, newpage = F)
popViewport()
pushViewport(viewport(layout.pos.col = 4))
grid.segments(0, 0, 1, 1)
popViewport()
pushViewport(viewport(layout.pos.col = 5:7))
grid.draw(rect)
print(p.peak.grey, vp = rect_vp, newpage = F)
popViewport()
pushViewport(viewport(layout.pos.col = 7:8))
inner.arrow <- arrow(angle = 10, type = "closed", length = unit(0.1, "npc"))
grid.segments(0.3, 0.5, 0.7, 0.5, arrow = inner.arrow)
popViewport()
pushViewport(viewport(layout.pos.col = 8:10))
print(p.ring, newpage = F)
## ------------------------------------- 
upViewport(0)
downViewport("fig1.layout")
pushViewport(viewport(layout.pos.col = 3, name = "fig1.2"))
pushViewport(viewport(layout = grid.layout(1, 7)))
pushViewport(viewport(layout.pos.col = 1:4))
grid.draw(few.rect)
print(p.peak.yellow, vp = few.rect_vp, newpage = F)
popViewport()
pushViewport(viewport(layout.pos.col = 4:5))
grid.segments(0.3, 0.5, 0.7, 0.5, arrow = inner.arrow)
popViewport()
pushViewport(viewport(layout.pos.col = 5:7))
print(p.ratio, newpage = F)
## ----------------------------------------------------------------------
upViewport(0)
downViewport("cross3")
pushViewport(viewport(layout.pos.row = 2, name = "score"))
grid.draw(module)
pushViewport(viewport(layout = grid.layout(5, 3)))
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1, name = "subtitle_2"))
grid.text("Score", gp = subtitle_gp)
## ------------------------------------- 
popViewport()
pushViewport(viewport(layout.pos.row = 2:5, layout.pos.col = 1:3, name = "fig2"))
pushViewport(viewport(layout = grid.layout(1, 10), name = "fig2.layout"))
pushViewport(viewport(layout.pos.col = 2:3, name = "fig2.1"))
grid.draw(few.rect)
pushViewport(few.rect_vp)
grid.draw(struc_2095)
popViewport(2)
pushViewport(viewport(layout.pos.col = 4))
grid.segments(0.1, 0.5, 0.9, 0.5, arrow = inner.arrow)
popViewport()
pushViewport(viewport(layout.pos.col = 5:6))
print(p.box, newpage = F)
popViewport()
pushViewport(viewport(layout.pos.col = 7))
grid.segments(0.1, 0.5, 0.9, 0.5, arrow = inner.arrow)
popViewport()
pushViewport(viewport(layout.pos.col = 8:9))
print(p.ratio, newpage = F)
## ---------------------------------------------------------------------- 
upViewport(0)
downViewport("cross3")
pushViewport(viewport(layout.pos.row = 3, name = "identical"))
grid.draw(module)
pushViewport(viewport(layout = grid.layout(5, 3)))
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1, name = "subtitle_3"))
grid.text("Identical", gp = subtitle_gp)


